# This is a basic workflow to help you get started with Actions

name: My Testing Workflow #1

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Triggered by any review request
  pull_request:
    types: [opened, review_requested]

jobs:
  my_job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'A review was requested'
      - name: Install cf-remote
        run: pip3 install cf-remote
      - name: Install CFEngine Hub Version Master
        run: sh ./install-cfengine-hub-version-master.sh
      - name: Check for Pass and not FAILED
        run: sh ./check-each-cf-emits-Pass-not-FAIL.sh
